project_id = "raarimsxmcqsnamwdfov"

[functions.inventory-predictions]
verify_jwt = false

[functions.send-po-email]
verify_jwt = false

[functions.send-inventory-alerts]
verify_jwt = false

[functions.send-scheduled-reports]
verify_jwt = false